name: barril_app
description: Sistema de pedidos para restaurante carne al barril
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  drift: ^2.18.0
  drift_flutter: ^0.2.0
  sqlite3_flutter_libs: ^0.5.0
  get_it: ^8.0.0
  permission_handler: ^11.3.1
  flutter_blue_plus: ^1.32.12
  esc_pos_utils_plus: ^2.0.2
  pdf: ^3.11.0
  printing: ^5.13.0
  share_plus: ^10.0.0
  file_picker: ^8.1.2
  image: ^4.2.0
  path_provider: ^2.1.4
  csv: ^6.0.0
  uuid: ^4.4.2
  intl: ^0.19.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  drift_dev: ^2.18.0
  riverpod_generator: ^2.4.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true
  image_path: assets/images/posify_icon.png
  adaptive_icon_background: "#1E9E4A"
  adaptive_icon_foreground: assets/images/posify_icon.png
